CREATE TYPE public.account_type AS ENUM
    ('Client', 'Employee', 'Admin');

ALTER TYPE public.account_type
    OWNER TO cse340;

-- Table structure for table 'classification'
CREATE TABLE public.classification (
	classification_id INT GENERATED BY DEFAULT AS IDENTITY,
	classification_name CHARACTER VARYING NOT NULL,
	CONSTRAINT classification_pk PRIMARY KEY (classification_id)
)

-- Table structure for table `inventory`
create table if not exists public.inventory (
    inv_id integer not null generated by default as identity,
    inv_make character varying not null,
    inv_model character varying not null,
    inv_year character(4) not null,
    inv_description text not null,
    inv_image character varying not null,
    inv_thumbnail character varying not null,
    inv_price numeric(9, 0) not null,
    inv_miles integer not null,
    inv_color character varying not null,
    classification_id integer not null,
    constraint inventory_pkey primary key (inv_id)
);

-- Create relationship between `classification` and `inventory` tables
alter table if exists public.inventory
add constraint fk_classification foreign key (classification_id) references public.classification (classification_id) 
match simple on update cascade on delete no action;


-- Table structure for table `account`
create table if not exists public.account (
    account_id integer not null generated by default as identity,
    account_firstname character varying not null,
    account_lastname character varying not null,
    account_email character varying not null,
    account_password character varying not null,
    account_type account_type not null default 'Client'::account_type,
    constraint account_pkey primary key (account_id)
);


INSERT INTO public.classification (classification_name)
VALUES ('Custom'),('Sport'),('SUV'),('Truck'),('Sedan');